"""Column contracts and domain mappings for the AQX_P_488 dataset."""

SOURCE_COLUMNS = (
    "sitename",
    "county",
    "aqi",
    "pollutant",
    "status",
    "so2",
    "so2_avg",
    "co",
    "co_8hr",
    "o3",
    "o3_8hr",
    "pm10",
    "pm10_avg",
    "pm2.5",
    "pm2.5_avg",
    "no2",
    "nox",
    "no",
    "windspeed",
    "winddirec",
    "datacreationdate",
    "longitude",
    "latitude",
    "siteid",
    "unit",
)

NUMERIC_COLUMNS = (
    "aqi",
    "so2",
    "so2_avg",
    "co",
    "co_8hr",
    "o3",
    "o3_8hr",
    "pm10",
    "pm10_avg",
    "pm2.5",
    "pm2.5_avg",
    "no2",
    "nox",
    "no",
    "windspeed",
    "winddirec",
    "longitude",
    "latitude",
    "siteid",
)

TEXT_COLUMNS = ("sitename", "county", "pollutant", "status", "unit")

MISSING_MARKERS = ("", "nan", "NaN", "NAN", "null", "NULL", "None", "-")

COUNTY_MAP = {
    "Changhua County": "彰化縣",
    "Chiayi City": "嘉義市",
    "Chiayi County": "嘉義縣",
    "Hsinchu City": "新竹市",
    "Hsinchu County": "新竹縣",
    "Hualien County": "花蓮縣",
    "Kaohsiung City": "高雄市",
    "Keelung City": "基隆市",
    "Kinmen County": "金門縣",
    "Lienchiang County": "連江縣",
    "Miaoli County": "苗栗縣",
    "Nantou County": "南投縣",
    "New Taipei City": "新北市",
    "Penghu County": "澎湖縣",
    "Pingtung County": "屏東縣",
    "Taichung City": "臺中市",
    "Tainan City": "臺南市",
    "Taipei City": "臺北市",
    "Taitung County": "臺東縣",
    "Taoyuan County": "桃園市",
    "Yilan County": "宜蘭縣",
    "Yunlin County": "雲林縣",
}

STATUS_MAP = {
    "Good": "GOOD",
    "良好": "GOOD",
    "Moderate": "MODERATE",
    "普通": "MODERATE",
    "Unhealthy for Sensitive Groups": "UNHEALTHY_FOR_SENSITIVE_GROUPS",
    "對敏感族群不健康": "UNHEALTHY_FOR_SENSITIVE_GROUPS",
    "Unhealthy": "UNHEALTHY",
    "對所有族群不健康": "UNHEALTHY",
    "Very Unhealthy": "VERY_UNHEALTHY",
    "非常不健康": "VERY_UNHEALTHY",
    "Hazardous": "HAZARDOUS",
    "危害": "HAZARDOUS",
}

POLLUTANT_MAP = {
    "PM2.5": "PM2.5",
    "細懸浮微粒": "PM2.5",
    "PM10": "PM10",
    "懸浮微粒": "PM10",
    "O3": "O3",
    "臭氧": "O3",
    "O3,8h": "O3_8H",
    "臭氧八小時": "O3_8H",
    "CO": "CO",
    "一氧化碳": "CO",
    "SO2": "SO2",
    "二氧化硫": "SO2",
    "NO2": "NO2",
    "二氧化氮": "NO2",
}

OUTPUT_COLUMNS = (
    "source_file",
    "source_row_number",
    "source_site_id",
    "site_name",
    "county",
    "observed_at",
    "aqi",
    "status_code",
    "primary_pollutant",
    "so2",
    "so2_avg",
    "co",
    "co_8hr",
    "o3",
    "o3_8hr",
    "pm10",
    "pm10_avg",
    "pm25",
    "pm25_avg",
    "no2",
    "nox",
    "no",
    "wind_speed",
    "wind_direction",
    "longitude",
    "latitude",
    "unit",
    "quality_flags",
)
